# Generated by Django 4.2.7 on 2025-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_branch', models.CharField(max_length=50)),
            ],
        ),
    ]
