# Generated by Django 5.2.3 on 2025-06-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField()),
                ('e_name', models.CharField(max_length=200)),
                ('e_email', models.EmailField(max_length=100)),
                ('e_branch', models.CharField(max_length=100)),
            ],
        ),
    ]
